# Generated by Django 5.2.8 on 2025-11-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_password_code_profile_code4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='code4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gmail_code',
        ),
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
