# Generated by Django 5.2.8 on 2025-11-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_profile_code4_remove_profile_gmail_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='secret_code',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
